jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu latest'
    variables:
      NODE_VERSION: 10.15.3
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true

    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - task: NodeTool@0
        inputs:
          versionSpec: '10.15.3'
        displayName: 'TOOLS: install Node.js'
      - script: sudo npm install -g npm
        displayName: 'TOOLS: update NPM'
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      - script: npm install
        displayName: 'INSTALL: launch npm install'
      #----------------------------------------------------------------------
      # Production build
      #----------------------------------------------------------------------
      - script: ./mvnw package -Pprod -DskipTests
        displayName: 'BUILD: creating production build'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'target'
          Contents: '*.jar'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: bugtracker